// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyKho.Models;

public partial class OutputInfo
{
    public string Id { get; set; }

    public string IdObject { get; set; }

    public string IdInputInfo { get; set; }

    public int IdCustomer { get; set; }

    public int? Count { get; set; }

    public string Status { get; set; }

    public virtual Customer IdCustomerNavigation { get; set; }

    public virtual InputInfo IdInputInfoNavigation { get; set; }

    public virtual Object IdObjectNavigation { get; set; }
}