// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyKho.Models;

public partial class Output
{
    public string Id { get; set; }

    public DateTime? DateOutput { get; set; }
}