// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using QuanLyKho.ViewModels;
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace QuanLyKho.Models;

public partial class Suplier : BaseViewModel
{
    public int Id { get; set; }

    private string _displayName;
    public string DisplayName { get => _displayName; set { _displayName = value; OnPropertyChanged(); } }

    private string _address;
    public string Address { get => _address; set { _address = value; OnPropertyChanged(); } }

    private string _phone;
    public string Phone { get => _phone; set { _phone = value; OnPropertyChanged(); } }

    private string _email;
    public string Email { get => _email; set { _email = value; OnPropertyChanged(); } }

    private string _moreInfo;
    public string MoreInfo { get => _moreInfo; set { _moreInfo = value; OnPropertyChanged(); } }

    public DateTime? ContractDate { get; set; }

    public virtual ICollection<Object> Objects { get; set; } = new List<Object>();
}
