// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using QuanLyKho.ViewModels;
using System;
using System.Collections.Generic;

namespace QuanLyKho.Models;

public partial class Unit : BaseViewModel
{
    public int Id { get; set; }

    private string _displayName;
    public string DisplayName { get => _displayName; set { _displayName = value; OnPropertyChanged(); } }

    public virtual ICollection<Object> Objects { get; set; } = new List<Object>();
}