// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyKho.Models;

public partial class User
{
    public int Id { get; set; }

    public string DisplayName { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public int IdRole { get; set; }

    public virtual UserRole IdRoleNavigation { get; set; }
}